Add P3 and P4 gramar
retkiewi/quadrangularMeshGrammar pull request #9
Opened 2022-12-09 22:08 UTC by Derstilon

2022-12-15 22:16 UTC, rozchlastywacz commented on productions/decorators.py
> +    return outer
@retkiewi finding matching isomorphism should be in the decorator, right? because now it is in the `apply` method of P4

2022-12-28 18:02 UTC, retkiewi commented on productions/decorators.py
> +    return outer
Yeppers

2023-01-13 11:07 UTC, ostatni5 commented on productions/decorators.py
> +    return outer
Noppers

2023-01-13 11:20 UTC, retkiewi commented on productions/decorators.py
> +    return outer
¯\_(ツ)_/¯

2023-01-13 11:29 UTC, retkiewi requested changes

2023-01-13 11:29 UTC, retkiewi commented on productions/decorators.py
> +    return outer
Please make this consistent with other productions. Each production should be decorated with an appropriate decorator that takes the whole graph and returns the isomorphism to which the production should be applied.

2023-01-13 13:33 UTC, retkiewi approved these changes

2023-01-13 16:52 UTC, Derstilon commented
@michal367 ready for merge

2023-01-13 17:03 UTC, merged